"""normalization_type en metadata_fields

Revision ID: 77d34e955845
Revises: b3e9f1a2c5d7
Create Date: 2026-08-29 01:32:42.754971

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = '77d34e955845'
down_revision: Union[str, None] = 'b3e9f1a2c5d7'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('metadata_fields', sa.Column('normalization_type', sa.String(length=100), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('metadata_fields', 'normalization_type')
    # ### end Alembic commands ###